name: Deploy to GitHub Pages

permissions:
  id-token: write
  pages: write

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: extractions/setup-just@v2
        with:
          just-version: '1.4.0'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version-file: "pyproject.toml"

      - name: Generate static site
        run: |
          uv run just gen

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Or your desired Node.js version

      - name: Install npm dependencies
        run: npm install

      - name: Build Tailwind CSS
        run: npm run build:css  # Or your Tailwind build command

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: website/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
